In [1]:
from transformers import AutoTokenizer

In [2]:
tokenizer = AutoTokenizer.from_pretrained("google-bert/bert-base-uncased")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

C:\Users\Manisha\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Manisha\.cache\huggingface\hub\models--google-bert--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [3]:
input_text = "Please enter sample text to tokenize"
print(input_text)

Please enter sample text to tokenize


In [4]:
# tokenize input
token = tokenizer(input_text)
print(token)

{'input_ids': [101, 3531, 4607, 7099, 3793, 2000, 19204, 4697, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [8]:
tokenizer.decode(token['input_ids'])

'[CLS] please enter sample text to tokenize [SEP]'

In [9]:
tokenizer.decode(token['token_type_ids'])

'[PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]'

In [10]:
tokenizer.decode(token['attention_mask'])

'[unused0] [unused0] [unused0] [unused0] [unused0] [unused0] [unused0] [unused0] [unused0]'

In [12]:
print(token['input_ids'])
print(type(token['input_ids']))

[101, 3531, 4607, 7099, 3793, 2000, 19204, 4697, 102]
<class 'list'>


In [16]:
token=tokenizer(input_text, return_tensors='np')
print(token['input_ids'])
print(type(token['input_ids']))

[[  101  3531  4607  7099  3793  2000 19204  4697   102]]
<class 'numpy.ndarray'>


In [17]:
token=tokenizer(input_text, return_tensors='pt')
print(token['input_ids'])
print(type(token['input_ids']))

tensor([[  101,  3531,  4607,  7099,  3793,  2000, 19204,  4697,   102]])
<class 'torch.Tensor'>


In [18]:
# TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. 
# We recommend migrating to PyTorch classes or pinning your version of Transformers.
# token=tokenizer(input_text, return_tensors='tf')
# print(token['input_ids'])
# print(type(token['input_ids']))

TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.


tf.Tensor([[  101  3531  4607  7099  3793  2000 19204  4697   102]], shape=(1, 9), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [35]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

C:\Users\Manisha\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Manisha\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [36]:
print("model_max_length ",tokenizer.model_max_length)
print("vocab_size ",tokenizer.vocab_size)
print("is_fast ",tokenizer.is_fast)
print("model_input_names ",tokenizer.model_input_names)
print("padding_side ",tokenizer.padding_side)
print("truncation_side ",tokenizer.truncation_side)

model_max_length  512
vocab_size  30522
is_fast  True
model_input_names  ['input_ids', 'token_type_ids', 'attention_mask']
padding_side  right
truncation_side  right


In [37]:
# special tokens
print('[CLS] Token:', tokenizer.cls_token, ('ID:', tokenizer.cls_token_id))
print('[PAD] Token:', tokenizer.pad_token, ('ID:', tokenizer.sep_token_id))
print('[SEP] Token:', tokenizer.sep_token, ('ID:', tokenizer.pad_token_id))
print('[UNK] Token:', tokenizer.unk_token, ('ID:', tokenizer.unk_token_id))
print('[MASK] Token:', tokenizer.mask_token, ('ID:', tokenizer.mask_token_id))

[CLS] Token: [CLS] ('ID:', 101)
[PAD] Token: [PAD] ('ID:', 102)
[SEP] Token: [SEP] ('ID:', 0)
[UNK] Token: [UNK] ('ID:', 100)
[MASK] Token: [MASK] ('ID:', 103)


In [39]:
tokenizer = AutoTokenizer.from_pretrained("roberta-base")

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

C:\Users\Manisha\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Manisha\.cache\huggingface\hub\models--roberta-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [42]:
print("(default model max length) model_max_length ",tokenizer.model_max_length)
print("vocab_size ",tokenizer.vocab_size)
print("is_fast ",tokenizer.is_fast)
print("model_input_names ",tokenizer.model_input_names)
print("padding_side ",tokenizer.padding_side)
print("truncation_side ",tokenizer.truncation_side)

(default model max length) model_max_length  512
vocab_size  50265
is_fast  True
model_input_names  ['input_ids', 'attention_mask']
padding_side  right
truncation_side  right


In [41]:
# special tokens
print('[CLS] Token:', tokenizer.cls_token, ('ID:', tokenizer.cls_token_id))
print('[PAD] Token:', tokenizer.pad_token, ('ID:', tokenizer.sep_token_id))
print('[SEP] Token:', tokenizer.sep_token, ('ID:', tokenizer.pad_token_id))
print('[UNK] Token:', tokenizer.unk_token, ('ID:', tokenizer.unk_token_id))
print('[MASK] Token:', tokenizer.mask_token, ('ID:', tokenizer.mask_token_id))

[CLS] Token: <s> ('ID:', 0)
[PAD] Token: <pad> ('ID:', 2)
[SEP] Token: </s> ('ID:', 1)
[UNK] Token: <unk> ('ID:', 3)
[MASK] Token: <mask> ('ID:', 50264)


In [55]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

input_text = "Please enter sample text to tokenize"
token=tokenizer.tokenize(input_text)
print(token)

['please', 'enter', 'sample', 'text', 'to', 'token', '##ize']


In [56]:
input_ids = tokenizer.convert_tokens_to_ids(token)
print(input_ids)

[3531, 4607, 7099, 3793, 2000, 19204, 4697]


In [57]:
# special tokens
out = tokenizer.prepare_for_model(input_ids)
special_tokens=out['input_ids']
print(special_tokens)

You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


[101, 3531, 4607, 7099, 3793, 2000, 19204, 4697, 102]


In [58]:
print(tokenizer.decode(special_tokens))

[CLS] please enter sample text to tokenize [SEP]


In [69]:
tokenizer = AutoTokenizer.from_pretrained("roberta-base")

input_text = "Please enter sample text to tokenize"
token=tokenizer.tokenize(input_text)
print(token)

['Please', 'Ġenter', 'Ġsample', 'Ġtext', 'Ġto', 'Ġtoken', 'ize']


In [70]:
# special tokens
out = tokenizer.prepare_for_model(input_ids)
special_tokens=out['input_ids']
print(special_tokens)

You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


[0, 6715, 2914, 7728, 2788, 7, 19233, 2072, 2]


In [71]:
input_ids = tokenizer.convert_tokens_to_ids(token)
print(input_ids)

[6715, 2914, 7728, 2788, 7, 19233, 2072]


In [72]:
print(tokenizer.decode(special_tokens))

<s>Please enter sample text to tokenize</s>


In [73]:
input_ids = tokenizer.convert_tokens_to_ids(token)
print(input_ids)

[6715, 2914, 7728, 2788, 7, 19233, 2072]


In [74]:
print(tokenizer.decode(special_tokens))

<s>Please enter sample text to tokenize</s>


In [75]:
batched_sentences = [
    "But what about second breakfast?",
    "Don't think he knows about second breakfast, Pip.",
    "What about elevensies?",
    "This is a much longer sentence that will definitely need to be truncated.",
    "Another sentence."
]
batched_sentences

['But what about second breakfast?',
 "Don't think he knows about second breakfast, Pip.",
 'What about elevensies?',
 'This is a much longer sentence that will definitely need to be truncated.',
 'Another sentence.']

In [76]:
print("(default model max length) model_max_length ",tokenizer.model_max_length)

(default model max length) model_max_length  512


In [91]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

In [92]:
tokenizer_inputs = tokenizer(batched_sentences, padding=True, return_tensors='pt')
print(tokenizer_inputs)

{'input_ids': tensor([[  101,  2021,  2054,  2055,  2117,  6350,  1029,   102,     0,     0,
             0,     0,     0,     0,     0,     0],
        [  101,  2123,  1005,  1056,  2228,  2002,  4282,  2055,  2117,  6350,
          1010, 28315,  1012,   102,     0,     0],
        [  101,  2054,  2055,  5408, 14625,  1029,   102,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [  101,  2023,  2003,  1037,  2172,  2936,  6251,  2008,  2097,  5791,
          2342,  2000,  2022, 25449,  1012,   102],
        [  101,  2178,  6251,  1012,   102,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': t

In [93]:
print(tokenizer_inputs['input_ids'])

tensor([[  101,  2021,  2054,  2055,  2117,  6350,  1029,   102,     0,     0,
             0,     0,     0,     0,     0,     0],
        [  101,  2123,  1005,  1056,  2228,  2002,  4282,  2055,  2117,  6350,
          1010, 28315,  1012,   102,     0,     0],
        [  101,  2054,  2055,  5408, 14625,  1029,   102,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [  101,  2023,  2003,  1037,  2172,  2936,  6251,  2008,  2097,  5791,
          2342,  2000,  2022, 25449,  1012,   102],
        [  101,  2178,  6251,  1012,   102,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]])


In [94]:
# 5 no of sentences
# 17 sequence length
print(tokenizer_inputs['input_ids'].shape)

torch.Size([5, 16])


In [95]:
for i, inputs in enumerate(tokenizer_inputs['input_ids']):
    print(f"sentence {i+1}",tokenizer.decode(inputs))

sentence 1 [CLS] but what about second breakfast? [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]
sentence 2 [CLS] don ' t think he knows about second breakfast, pip. [SEP] [PAD] [PAD]
sentence 3 [CLS] what about elevensies? [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]
sentence 4 [CLS] this is a much longer sentence that will definitely need to be truncated. [SEP]
sentence 5 [CLS] another sentence. [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]


In [96]:
try:
    tokenizer_inputs = tokenizer(batched_sentences, truncation=True, return_tensors='pt')
except Exception as e:
    print(f'An Error occured : {e}')

An Error occured : Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`input_ids` in this case) have excessive nesting (inputs type `list` where type `int` is expected).


In [99]:
tokenizer_inputs = tokenizer(batched_sentences, 
                             padding='max_length',
                             max_length=20,
                             truncation=True, 
                             return_tensors='pt')


In [102]:
for i, inputs in enumerate(tokenizer_inputs['input_ids']):
    print(len(inputs), inputs)
    print(f"sentence {i+1}",tokenizer.decode(inputs))
    print("-"*20)

20 tensor([ 101, 2021, 2054, 2055, 2117, 6350, 1029,  102,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0])
sentence 1 [CLS] but what about second breakfast? [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]
--------------------
20 tensor([  101,  2123,  1005,  1056,  2228,  2002,  4282,  2055,  2117,  6350,
         1010, 28315,  1012,   102,     0,     0,     0,     0,     0,     0])
sentence 2 [CLS] don ' t think he knows about second breakfast, pip. [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]
--------------------
20 tensor([  101,  2054,  2055,  5408, 14625,  1029,   102,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0])
sentence 3 [CLS] what about elevensies? [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]
--------------------
20 tensor([  101,  2023,  2003,  1037,  2172,  2936,  6251,  2008,  2097,  5791,
         2342,  2000,  2022, 2544